package frc.robot.subsystems.leds;

import edu.wpi.first.wpilibj.util.Color;

/** Constants for the status LED strip (addr                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               vcessable LEDs on PWM). */
public final class LEDConstants {
  private LEDConstants() {}

  public static final int kPort = 0;
  public static final int kLength = 30;
  public static final Color kPurple = new Color(128, 0, 128);
  public static final Color kNavyBlue = new Color(0, 0, 80);
  public static final Color kGold = new Color(255, 200, 50);
  public static final Color kLimeGreen = new Color(0, 255, 0);
  public static final Color kOrange = new Color(255, 165, 0);
}
